// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CarDetailResponse struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Brand string  `json:"brand"`
	Year  string  `json:"year"`
	Price float64 `json:"price"`
}

type CreateCarRequest struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Brand string  `json:"brand"`
	Year  string  `json:"year"`
	Price float64 `json:"price"`
}

type GetCar struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}
